"""
run_step6.py  --  F.10 Step 6 (fallback weave) runner, first growing pass
==========================================================================
Runs Fall_Back_Logic.py to produce the first FRESH blended elasticity per
ProductKey on growing Cluster+Site data. This is the documented momentum
shortcut (Alternative A): the elasticities are growing, but three inputs are
frozen placeholders (see verify_provenance + FD.11/14/15). The result is a
PRELIMINARY fresh read -- the provenance receipt already labels it REVIEW so
nobody over-trusts it.

What it does
------------
1. PREFLIGHT: check all six Step 6 inputs Constant.py expects. Place the three
   that aren't where Step 6 looks, from their known sources (logging growing vs
   frozen per file). Refuse to run if any source is missing.
2. RUN Fall_Back_Logic.py with the right interpreter, chdir'd into the Step 6
   folder so its relative Constant.py paths resolve. AppLocker-clean (no .exe).
3. VERIFY (R7): confirm Final_Fallback_Data*.xlsx was produced, row count, and
   -- the headline -- the elasticity_level (F1-F7) distribution. That distribution
   directly answers the FD.11 bundle-revisit trigger: how often does F2/F4 (bundle)
   win as the chosen source? If rarely -> bundle stays parked with evidence.

Input placement (what goes where Constant.py looks)
---------------------------------------------------
  blended_model   <- Cluster step 1-4 GROWING (_archive pg4fix output_summary.xlsx)
                     renamed to output_summary_ready.xlsx (Step 6 expects '_ready')
  blended_output  <- Cluster step-5 FROZEN (_Ivce facit)            [FD.15]
  bundle_cluster  <- Bundle FROZEN (OneDrive facit output_summary_bundle.xlsx) [FD.11]
  df_all_product  : already in place (frozen facit)                 [FD.14]
  prod_site       : already in place (growing 2026-06-10)
  df_product      : generated by Step 6 itself at runtime (not placed)

Usage
-----
    cd "C:\\Projekt\\BCG"
    py -3.11 run_step6.py            # preflight + place + run + verify
    py -3.11 run_step6.py --dry-run  # preflight + show placement plan only

Developer: Jens Palmo (Senior Business Analyst, Evidensia Djursjukvard AB)
Author: Claude advisor, 2026-06-11.
"""
import argparse
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path

REPO = Path(r"C:\Projekt\BCG")
ELAST = REPO / "Pipeline" / "02. Elasticity"
FBL = ELAST / "6. Fall Back Logic"
ONEDRIVE_FACIT = (
    Path("C:/Users/jepa02/OneDrive - Evidensia Djursjukvård AB/Datastrategi/BCG")
    / "BCG_orginal_V2_New" / "02. Elasticity" / "6. Fall Back Logic" / "input_data"
)


def log(tag, msg):
    print(f"[{tag}] {msg}", flush=True)


def _place_file(p, dry_run):
    """Copy a source into the destination Step 6 expects. For the Cluster
    blended_model, also split its KEY column into Cluster + ItemCode, because our
    growing output_summary carries only KEY ('Clinics 0-AAP115') while Step 6's
    read_blended_model_data expects an ItemCode column to rename to ProductKey
    (BCG's facit had it pre-split; our raw model output does not). This adaptation
    lives in the runner so Fall_Back_Logic.py stays untouched.
    Split on the LAST '-' (rsplit) -- cluster names contain spaces but no hyphens,
    ItemCodes contain no hyphens; matches rationality helper's extract_cluster_from_key.
    """
    import pandas as pd

    if dry_run:
        return

    p["dest"].parent.mkdir(parents=True, exist_ok=True)

    if p.get("split_key"):
        df = pd.read_excel(p["src"])
        if "KEY" in df.columns and "ItemCode" not in df.columns:
            parts = df["KEY"].astype(str).str.rsplit("-", n=1)
            df["Cluster"] = parts.str[0]
            df["ItemCode"] = parts.str[1]
            log("   ", f"     split KEY -> Cluster + ItemCode ({len(df):,} rows)")
        df.to_excel(p["dest"], index=False, engine="openpyxl")
    else:
        shutil.copy2(p["src"], p["dest"])


# (label, destination Step 6 expects, source, kind, fd)
PLACEMENTS = [
    {
        "label": "blended_model (Cluster step 1-4)",
        "dest": ELAST / "2. Product Cluster Level Models" / "output" / "output_summary_ready.xlsx",
        "src": ELAST / "2. Product Cluster Level Models" / "_archive_growing_2026-04-27_v2_pg4fix" / "output_summary.xlsx",
        "kind": "LIVE GROWING",
        "fd": "-",
        "split_key": True,   # growing output has KEY only; split -> Cluster + ItemCode for Step 6
    },
    {
        "label": "blended_output (Cluster step-5 blend)",
        "dest": ELAST / "2. Product Cluster Level Models" / "output" / "final_model_cluster_granularity.xlsx",
        "src": FBL / "input_data" / "final_model_cluster_granularity_Ivce.xlsx",
        "kind": "FROZEN (FD.15)",
        "fd": "FD.15",
    },
    {
        "label": "bundle_cluster (Bundle model)",
        "dest": ELAST / "5. Bundle Clinic Models" / "output" / "model" / "output_summary.xlsx",
        "src": FBL / "input_data" / "output_summary_bundle.xlsx",  # overlevnadstes: PULL fyller denna fran Blob (ej OneDrive)
        "kind": "FROZEN (FD.11)",
        "fd": "FD.11",
    },
]

# Inputs already in place (verify present, do not move).
ALREADY = [
    {"label": "df_all_product (weave weights)", "path": FBL / "input_data" / "Complete_Product_Data.xlsx", "kind": "FROZEN (FD.14)"},
    {"label": "prod_site (Site model)", "path": ELAST / "3. Product Site Level Models" / "output" / "model" / "output_summary.xlsx", "kind": "LIVE GROWING"},
]


def preflight(dry_run: bool) -> bool:
    log("PREFLIGHT", "checking Step 6 inputs ...")
    ok = True

    for a in ALREADY:
        if a["path"].exists():
            log("OK", f"{a['label']:<34} [{a['kind']}] in place")
        else:
            log("MISSING", f"{a['label']:<34} expected at {a['path']}")
            ok = False

    for p in PLACEMENTS:
        if not p["src"].exists():
            log("MISSING-SRC", f"{p['label']:<34} source not found: {p['src']}")
            ok = False
            continue
        action = "would place" if dry_run else "placing"
        log("PLACE", f"{p['label']:<34} [{p['kind']}] {action}")
        log("   ", f"     from: {p['src']}")
        log("   ", f"     to:   {p['dest']}")
        _place_file(p, dry_run)

    if not ok:
        log("ABORT", "one or more inputs/sources missing -- Step 6 cannot run")
    return ok


def run_step6() -> int:
    script = FBL / "Fall_Back_Logic.py"
    if not script.exists():
        log("ERROR", f"Fall_Back_Logic.py not found at {script}")
        return 1
    log("RUN", f"executing {script.name} (cwd={FBL}) ...")
    # chdir into the Step 6 folder so Constant.py's relative paths resolve.
    proc = subprocess.run(
        [sys.executable, str(script)],
        cwd=str(FBL),
        capture_output=True, text=True, encoding="utf-8", errors="replace",
        timeout=1800,
    )
    if proc.stdout:
        print(proc.stdout.rstrip())
    if proc.returncode != 0:
        # Known-benign case (LB.53): Final_Fallback_Data is written (rows 671/686)
        # BEFORE the cosmetic template/named-range write (row 691) that throws a
        # COM error when the Sweden_Fallback.xlsx template lacks the 'raw' name.
        # If the data file exists, the run SUCCEEDED on the part that matters.
        is_template_comerror = (
            "write_df_preserve_named_range" in (proc.stderr or "")
            or "com_error" in (proc.stderr or "").lower()
            or "wb.names" in (proc.stderr or "")
        )
        data_written = bool(
            list((FBL / "output_data").glob("Final_Fallback_Data*.xlsx"))
            or list(FBL.glob("Final_Fallback_Data*.xlsx"))
        )
        if is_template_comerror and data_written:
            log("RUN-WARN", "Fall_Back_Logic.py threw on the COSMETIC template write "
                            "(LB.53: Sweden_Fallback.xlsx named-range). The fallback DATA "
                            "was written before that step -- treating run as SUCCESS.")
            log("RUN-WARN", "Dashboard template NOT refreshed. To fix permanently, add the "
                            "'raw' named range to the template, or wrap the write in "
                            "try/wb.names.add. Data is unaffected.")
            return 0
        log("RUN-FAIL", f"exit {proc.returncode}")
        if proc.stderr:
            print("---- STDERR ----")
            print(proc.stderr.rstrip())
        return proc.returncode
    log("RUN-OK", "Fall_Back_Logic.py completed")
    return 0


def verify_output() -> int:
    """R7: trust the file, not the log. Find newest Final_Fallback_Data*.xlsx,
    report rows + elasticity_level (F1-F7) distribution = the FD.11 trigger signal."""
    import pandas as pd

    # Step 6 writes to output_path (.\output_data) and CWD; check both.
    candidates = list((FBL / "output_data").glob("Final_Fallback_Data*.xlsx")) + \
                 list(FBL.glob("Final_Fallback_Data*.xlsx"))
    if not candidates:
        log("VERIFY-FAIL", "no Final_Fallback_Data*.xlsx produced")
        return 1
    newest = max(candidates, key=lambda p: p.stat().st_mtime)
    log("VERIFY", f"newest output: {newest.name} ({newest.stat().st_size/1e6:.1f} MB)")

    df = pd.read_excel(newest)
    log("ROWS", f"{len(df):,} rows, {df['ProductKey'].nunique():,} distinct ProductKeys"
                 if "ProductKey" in df.columns else f"{len(df):,} rows")

    if "elasticity_level" in df.columns:
        log("F-LEVELS", "elasticity source distribution (the FD.11 bundle-trigger signal):")
        vc = df["elasticity_level"].value_counts(dropna=False)
        total = len(df)
        for lvl, n in vc.items():
            marker = "  <-- BUNDLE" if isinstance(lvl, str) and ("F2" in lvl or "F4" in lvl) else ""
            print(f"           {str(lvl):<32} {n:>8,}  ({100*n/total:5.1f}%){marker}")
        bundle_rows = df["elasticity_level"].astype(str).str.contains("F2|F4").sum()
        log("BUNDLE-WIN", f"F2/F4 (bundle) chosen for {bundle_rows:,} rows "
                          f"({100*bundle_rows/total:.1f}%) -- FD.11 revisit signal")
        if bundle_rows == 0:
            log("READ", "bundle NEVER wins -> parking is safe; bundle adds nothing the weave needs.")
        elif 100*bundle_rows/total < 3:
            log("READ", "bundle wins rarely (<3%) -> parking low-risk; revisit only if those KEYs matter.")
        else:
            log("READ", "bundle wins materially -> FD.11 revisit warranted; bundle rescues real KEYs.")

    if "final_elasticity" in df.columns:
        fe = pd.to_numeric(df["final_elasticity"], errors="coerce")
        log("ELAST", f"final_elasticity: median {fe.median():.3f}, "
                     f"negative {100*(fe<0).mean():.1f}%, "
                     f"in (-10,0) {100*((fe>-10)&(fe<0)).mean():.1f}%")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description="Run F.10 Step 6 fallback weave (first growing pass).")
    ap.add_argument("--dry-run", action="store_true", help="preflight + placement plan only, don't run")
    args = ap.parse_args()

    print("=" * 70)
    print("F.10 STEP 6 RUNNER  -  first growing pass (Alternative A)")
    print("Elasticities GROWING (Cluster+Site); weights/routing/bundle FROZEN.")
    print("Preliminary fresh read -- see verify_provenance receipt (REVIEW).")
    print("=" * 70)

    if not preflight(args.dry_run):
        return 1
    if args.dry_run:
        log("DRY-RUN", "placement plan shown; not running Step 6.")
        return 0

    rc = run_step6()
    if rc != 0:
        return rc
    return verify_output()


if __name__ == "__main__":
    sys.exit(main())
