# General Configuration
itr_name: "Ivce_2"

# Module paths for each model type
module_path: "../.."

# Imputation method
imputation:
  technique: "mean"

# Regular price calculation settings
regular_price:
  raw_input_data: "/data/0902_Sweden_weekly_model_data_site_level.csv"   #### Product site level raw data
  price_level: "Units"
  output_data: "/output/regular price/ivc_sweden_price.csv"
  in_scope_data: "/data/InScope Mapping.xlsx"

# Data preparation settings
data_preparation:
  raw_input_data: "/output/regular price/ivc_sweden_price.csv"
  sheet_name: "data"
  processed_data: "/output/data_original.csv"
  output_data: "/output/data_for_model.csv"
  transform_control: "code/control_files/transform_control_TT.csv"
  date_to_month_year_path: "/data/date_to_month_year_mapping.csv"
  competitor_data: "/output/regular price/0619_regular_price_TT_competitors.xlsx"
  competitor_sheet_name: "data"
  create_transform_control: False
  transform_control_save_path: "code/control_files/transform_control_TT.csv"

# Model execution configuration
model:
  raw_input_data: "/output/data_for_model.csv"
  control_file_path: "code/control_files/control_file.xlsx"
  model_summary_save_path: "/output/model/model_summary.xlsx"
  output_path: "/output/model/model_results.csv"
  output_summary_path: "/output/model/output_summary.xlsx"
  original_values: "/output/data_original.csv"

# Feature selection parameters
feature_selection:
  raw_input_data: "output/data_for_model.csv"
  mappings_file_path: "/data/input/"
  reference_file_name: "reference.csv"
  baseline_control_file: "baseline_control.csv"
  control_file_path: "code/control_files/control_file.xlsx"
  cols_to_try: ["major_holiday_count", "non_major_holiday_count", "YOY_SEASONALITY", "month_end_week", "negative_media_coverage_flag_mar24", "negative_media_coverage_flag_jan25"]
  cols_needed: ["CONST", "Regular_Price_fwbw_max_6", "Seasonality_KEY_fwbw_6", "Sum_FTE_Interpolated"]
  automl_summary: "output/model/automl/"
  automl_details: "output/model/automl/details/"
  selected_features_save_path: "output/model/automl/results/finalized_x_for_models.csv"
  all_features_save_path: "output/model/automl/results/all_x_for_models.csv"
  final_results: "output/model/automl/results/control_file.xlsx"

# Column types (shared by both models)
col_type:
  service: "str"
  ItemCode: "str"
  Prefix_Code: "str"
  ItemDescription: "str"
  Cluster: "str"
  Clusters: "str"
  week_starting_monday: "str"
  YearFlag: "str"
  negative_media_coverage_flag_jan25: "int64"
  negative_media_coverage_flag_mar24: "int64"
  Bundle_description: "str"
  Bundle_code: "str"
  Bundle_visits: "float64"
  basket_price: "float64"
  basket_revenue: "float64"
  bundle_visits_per_site: "float64"
  num_of_sites: "float64"
  No of Sites: "float64"
  SoldQuantity: "float64"
  NoofUnits: "float64"
  TotalNet: "float64"
  Emergency_Flag: "int64"
  negative_media_coverage_flag : 'int64'
  QuantitySold(SalesTotal>0): "float64"
  FTE_Interpolated: "float64"
  low_sales_sites: "int64"
  KEY: "str"
  key_service: "str"
  PRICE: "float64"
  Regular_Price_fwbw_max_6: "float64"
  ADJUSTED_REGULAR_PRICE: "float64"
  YEAR: "float64"
  MONTH: "float64"
  WEEK: "float64"
  HOLIDAY: "float64"
  major_holiday_count: "int64"
  non_major_holiday_count: "int64"
  OCCASION: "str"
  rest_holiday: "float64"
  month_end_week: "float64"
  unit_temp : 'float64'  
  Seasonality_KEY_fwbw_3 : 'float64'  
  Seasonality_KEY_fwbw_6 : 'float64'  
  Seasonality_KEY_fwbw_12 : 'float64'  
  Seasonality_KEY_fwbw_18 : 'float64'  
  Seasonality_KEY_fwbw_24 : 'float64'  
  DISCOUNT : 'float64'  
  CountDistinctNonNull_ItemCode : 'int64'
  Quarter_End : 'float64'  
  YOY_SEASONALITY : 'float64'  
  Productive_time_per_site: 'float64'
  week_rank: 'float64'
  first_week: 'float64'
  third_week: 'float64'
  wow_perc_change: 'float64'
  Sum_FTE_Interpolated : 'float64'
  TotalNetXVat: 'float64'

# Train-Test split and dependent variables
train_perc: 0.90
date_var: "week_starting_monday"
dep_var: "QuantitySold(SalesTotal>0)"
unique_key_var: "KEY"
model_group : 'KEY'
save_model: "/output/model/model_objects/"
rev_var: "TotalNet"

# Post-model summary preparation
output_summary_preparation:
  model_result: "/output/model/model_summary.xlsx"
  original_model_data: "/output/data_original.csv"
  product_description_path_Product_Site: "/data/item_description.xlsx"

### Ray Configuration
ray:
    cpus: 50
    memory : 80
    batch : 128
